### PR TITLE
Add middleware compatibility for django 1.11 and up

### PR DESCRIPTION
**Pull request by Thijss**

### CODE REVIEW

**Comment by gcushen** [comment]
@Thijss I assume `from django.utils.deprecation import MiddlewareMixin` is only present in Django v1.11+?

If so, we should state that Django v1.11+ is now required - such as by updating `setup.py` dependency version, `tox.ini` and `.travis.yml`...

**Comment by Thijss** [comment]
Sounds good. 
But then let's do it properly and rewrite the middleware to django-1.11 style.
I might be able to provide that code by the end of today.

Also, while you're at it, I'd update the mezzanine dependecy too, since version 4.3.0 is, I believe, the first version to officially support django 1.11

**Comment by gcushen** [comment]
@Thijss thanks, that would be great if you can rewrite the middleware to django-1.11 style and update the versions of dependencies :)

**Comment by Thijss** [comment]
Ok, I've added the commits to update the middleware and dependencies.

I'm not entirely sure what the ApiMiddleware is for, so I hope I implemented the middleware correctly.
It appears to be working fine for me though, running django 1.11 and mezzanine 4.3.0

If you want to check it yourself and are unfamiliar with the new middleware style, you can find the documentation here: https://docs.djangoproject.com/en/1.11/topics/http/middleware/#writing-your-own-middleware

**Comment by gcushen** [comment]
Thank you for your contribution @Thijss :)

**Pull request merged**
